release:
  image: docker:stable
  variables:
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:latest
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  services:
    - docker:dind
  script: |
    docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    docker pull ${CONTAINER_IMAGE} || true

    export WITH_MACOS="yes"
    export CACHE_FROM="--cache-from ${CONTAINER_IMAGE}"

    docker tag ${CONTAINER_IMAGE} evebox/builder:base

    ./docker.sh release

    tar zcvf resources-public.tar.gz ./resources/public

    ./docker.sh release-windows
    ./docker.sh release-macos

    mv dist/* .

    # Generate checksums.
    apk add openssl
    openssl sha256 *.tar.gz *.zip *.rpm *.deb > CHECKSUMS

    docker tag evebox/builder:latest ${CONTAINER_IMAGE}
    docker push ${CONTAINER_IMAGE}
  artifacts:
    paths:
      - "*.zip"
      - "*.rpm"
      - "*.deb"
      - "CHECKSUMS"
      - "resources-public.tar.gz"
